# Generated by Django 5.2.8 on 2025-12-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="messagecontactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
