# Generated by Django 5.2.8 on 2025-12-05 09:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reservations",
            new_name="Nobat",
        ),
        migrations.RenameModel(
            old_name="Reservation",
            new_name="ReservationDay",
        ),
        migrations.AlterModelOptions(
            name="nobat",
            options={"ordering": ("-time",), "verbose_name": ("Reservation List",)},
        ),
    ]
